---
- name: Extract files into the EC2 instance
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /var/local/bin

- name: Start the app
  become: true
  shell: npm install

- name: Stop default pm2
  become: true
  shell: pm2 stop default

- name: Start pm2
  become: true
  shell: pm2 start npm -- start